"""GATE 2 -- is the third cumulant INHERITED or GENERATED?

Decides whether a cumulant state has to be propagated at all.

At layer l+1 compare two estimates of c21(h_{l+1})[i,j] = cum(h_i, h_i, h_j):

  truth      the real network, sampled from x ~ N(0, I);
  generated  resample z ~ N(mu_l, Sigma_l) using the TRUE first two moments of
             h_l, then push through ReLU and W_{l+1}.  By construction this
             surrogate has kappa3(h_l) = 0, so any c21 it produces was
             manufactured by the ReLU acting on a Gaussian.

If generated ~= truth, then c21 is a function of (mu, Sigma) at every layer and
no cumulant state is needed -- the M40 closure's inputs become computable from
the Gaussian moments alone, which is the easy world.  If generated is far from
truth, the cumulant is genuinely inherited and must be propagated, which is the
hard world (and the one where the layer-1 exactness of Gate 1 matters, because
it supplies the recursion's initial condition).

Everything is accumulated in streaming fashion: materialising 2e6 x 256 in
float64 is 4 GB per array, and the first version of this script was OOM-killed.
"""

from __future__ import annotations

import sys

import numpy as np

sys.path.insert(0, "/Users/skyenygaard/Programming/AI-Safety/arc_whitebox/scripts")
from eval_sampling_official import DEFAULT_DATA, _load_rows  # noqa: E402

N_WIDTH = 256
CHUNK = 32768


def _stream_c21(gen_batches):
    """Two-pass streaming cum(h_i,h_i,h_j); gen_batches() yields fresh batches."""
    s1 = np.zeros(N_WIDTH)
    total = 0
    for H in gen_batches():
        s1 += H.sum(0)
        total += H.shape[0]
    mean = s1 / total
    C = np.zeros((N_WIDTH, N_WIDTH))
    for H in gen_batches():
        Z = H - mean
        C += (Z * Z).T @ Z
    return C / total


def real_next_pre(weights, layer, n_samples, seed):
    """Batches of h_{l+1} on the real network."""
    def gen():
        rng = np.random.default_rng(seed)
        done = 0
        while done < n_samples:
            b = min(CHUNK, n_samples - done)
            A = rng.standard_normal((b, N_WIDTH)).astype(np.float32)
            for li, W in enumerate(weights):
                H = A @ W
                A = np.maximum(H, 0.0)
                if li == layer:
                    yield (A.astype(np.float64)) @ weights[li + 1].astype(np.float64)
                    break
            done += b
    return gen


def real_layer_moments(weights, layer, n_samples, seed):
    """mu_l, Sigma_l of the real h_l, streamed."""
    s1 = np.zeros(N_WIDTH)
    s2 = np.zeros((N_WIDTH, N_WIDTH))
    rng = np.random.default_rng(seed)
    done = 0
    while done < n_samples:
        b = min(CHUNK, n_samples - done)
        A = rng.standard_normal((b, N_WIDTH)).astype(np.float32)
        for li, W in enumerate(weights):
            H = A @ W
            A = np.maximum(H, 0.0)
            if li == layer:
                Hd = H.astype(np.float64)
                s1 += Hd.sum(0)
                s2 += Hd.T @ Hd
                break
        done += b
    mu = s1 / n_samples
    return mu, s2 / n_samples - np.outer(mu, mu)


def gaussian_surrogate_next_pre(mu, sigma, next_weight, n_samples, seed):
    """Batches of h_{l+1} from z ~ N(mu, Sigma): kappa3(h_l) = 0 by construction."""
    ev, V = np.linalg.eigh(sigma)
    root = V * np.sqrt(np.maximum(ev, 0.0))
    w = next_weight.astype(np.float64)

    def gen():
        rng = np.random.default_rng(seed)
        done = 0
        while done < n_samples:
            b = min(CHUNK, n_samples - done)
            z = mu + rng.standard_normal((b, N_WIDTH)) @ root.T
            yield np.maximum(z, 0.0) @ w
            done += b
    return gen


def main() -> None:
    rows = _load_rows(DEFAULT_DATA, [0, 1, 2])
    n_samples = 1_500_000
    print("GATE 2: is c21 at layer l+1 inherited from kappa3(h_l) or generated by the ReLU?")
    print("  'generated' = resample z ~ N(mu_l, Sigma_l) with TRUE moments (kappa3 = 0),")
    print("  push through ReLU and W_{l+1}.\n")
    print(f"{'':>7}{'layer':>7}{'||c21|| truth':>15}{'||c21|| gen':>13}"
          f"{'rel err':>10}{'corr':>8}{'MC noise':>10}")
    for ri, (name, W, _) in enumerate(rows):
        for layer in (7, 15, 23):
            truth = _stream_c21(real_next_pre(W, layer, n_samples, 7 + ri))
            truth2 = _stream_c21(real_next_pre(W, layer, n_samples, 70007 + ri))
            mu, sigma = real_layer_moments(W, layer, n_samples, 7 + ri)
            gen = _stream_c21(
                gaussian_surrogate_next_pre(mu, sigma, W[layer + 1], n_samples, 555 + ri)
            )
            sc = np.sqrt(np.mean(truth ** 2))
            noise = np.sqrt(np.mean((truth - truth2) ** 2)) / np.sqrt(2) / sc
            rel = np.sqrt(np.mean((gen - truth) ** 2)) / sc
            corr = float(np.corrcoef(gen.ravel(), truth.ravel())[0, 1])
            print(f"{('MLP ' + str(ri)):>7}{layer + 1:>7}{sc:15.4e}"
                  f"{np.sqrt(np.mean(gen ** 2)):13.4e}{rel:10.4f}{corr:8.4f}{noise:10.4f}",
                  flush=True)
    print("""
Reading:
  rel err ~ MC noise  -> c21 is GENERATED; computable from (mu, Sigma) alone,
                         no cumulant state needed  [easy world]
  rel err >> MC noise -> c21 is INHERITED; must be propagated, and Gate 1's
                         exact layer-1 slice is the recursion's start [hard world]""")


if __name__ == "__main__":
    main()
