"""Canonical deterministic files covered by PROOF_MANIFEST.sha256."""

PROOF_FILES = [
    'README.md',
    'THEOREM_PROOF.md',
    'PROOF_AUDIT.md',
    'requirements.txt',
    'FULL_PROOF_REPRODUCE.sh',
    'auxiliary_coefficients_d256_L32_deg5.json',
    'formal_interval_certificate.py',
    'formal_meanvalue_certificate.py',
    'formal_proof_common.py',
    'formal_base_certificate.py',
    'formal_sign_chunk.py',
    'assemble_formal_certificate.py',
    'formal_kernel_mean.py',
    'formal_delsarte_bound.py',
    'formal_near_optimality_theorem.py',
    'verify_sign_logic.py',
    'generate_kerdock_multiplicity.py',
    'audit_formal_interval_arithmetic.py',
    'verify_theorem_package.py',
    'verify_manifest.py',
    'generate_manifest.py',
    'proof_file_list.py',
    'stationary_point_hints_d256_L32.json',
    'results/formal_base_certificate_d256_L32.json',
    'results/FORMAL_CERTIFICATE_D256_L32.json',
    'results/FORMAL_SIGN_LOGIC_AUDIT.json',
    'results/FORMAL_INTERVAL_AUDIT.json',
    'results/KERDOCK_MULTIPLICITY_PROOF.json',
    'results/FORMAL_KERNEL_MEAN_D256_L32.json',
    'results/FORMAL_DELSARTE_BOUND_D256_L32.json',
    'results/FORMAL_NEAR_OPTIMALITY_THEOREM_D256_L32.json',
    'results/THEOREM_PACKAGE_VERIFICATION.json',
]
